Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'bin/**/*'
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
