default: &default
  adapter: postgresql
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: review_manager_development

test:
  <<: *default
  database: review_manager_test

production:
  url: <%= ENV['DATABASE_URL'] %>
